- name: Install system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
    state: latest
    update_cache: true

- name: Wait for apt lock to be released
  shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
          fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || \
          fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
      echo "Waiting for other apt processes to finish..."
      sleep 5
    done
  changed_when: false

- name: Add Docker GPG key and repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker and Compose plugin
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
