version: '3'

services:
   mariadb:
      env_file:
         - .env
      build: ./requirements/mariadb
      container_name: mariadb
      image: mariadb
      restart: always
      ports:
         - "3306:3306"
      volumes:
         - mariadb_data:/var/lib/mysql
      networks:
         - my_network
      healthcheck: 
         test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
         interval: 10s
         retries: 5

   wordpress:
      env_file:
         - .env
      build: ./requirements/wordpress
      container_name: wordpress
      image: wordpress
      depends_on:
         - mariadb
      restart: always
      ports:
         - "9000:9000"
      volumes:
         - wordpress_data:/var/www/html
      networks:
         - my_network

   nginx:
      build: ./requirements/nginx
      container_name: nginx
      image: nginx
      depends_on:
         - wordpress
      ports:
         - "443:443"
      volumes:
         - wordpress_data:/var/www/html
      networks:
         - my_network
      restart: always

   phpmyadmin:
      build: ./requirements/phpmyadmin  
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
         - "8000:8000"
      depends_on:
         - mariadb
      volumes:
         - phpmyadmin_data:/usr/share/nginx/html/phpmyadmin
      environment:
         PMA_HOST: mariadb

         PMA_USER: said
         PMA_PORT: 3306            
         PMA_PASSWORD: 1234 
      networks:
         - my_network

volumes:
   wordpress_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/sriyani/Desktop/cloud/inception/data/WordPress
   mariadb_data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/sriyani/Desktop/cloud/inception/data/DB
   phpmyadmin_data:
      driver: local

networks:
  my_network:
    driver: bridge