- name: Create nginx data directory
  file:
    path: "{{ ansible_env.HOME }}/data/wordpress"
    state: directory
    mode: '0755'

- name: Copy inception project
  copy:
    src: "{{ inception_local_path }}/"
    dest: "{{ inception_remote_path }}/"
    mode: '0755'
    owner: root
    group: root

- name: Start nginx with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ inception_remote_path }}"
    services:
      - nginx
    build: "always"
