
FROM debian:buster


RUN apt-get -y update && apt-get -y install nginx openssl


RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=my-site.com"


COPY default /etc/nginx/sites-available/default

EXPOSE 443


CMD ["nginx", "-g", "daemon off;"]
