

FROM debian:buster



RUN apt-get update  && apt install nginx -y && apt-get update && apt-get install -y default-mysql-client && \
    apt-get install -y nginx php-fpm php-mysql wget unzip && \
    apt-get clean


RUN wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip -O /tmp/phpmyadmin.zip && \
    unzip /tmp/phpmyadmin.zip -d /usr/share/nginx/html && \
    mv /usr/share/nginx/html/phpMyAdmin-*-all-languages /usr/share/nginx/html/phpmyadmin && \
    rm /tmp/phpmyadmin.zip


RUN chown -R www-data:www-data /usr/share/nginx/html/phpmyadmin
COPY config.inc.php /usr/share/nginx/html/phpmyadmin/config.inc.php

# RUN mv /usr/share/nginx/html/phpmyadmin/ /var/www/html/
COPY default /etc/nginx/sites-enabled/default

EXPOSE 8000


CMD service php7.3-fpm start && nginx -g "daemon off;"
